'use strict';
const app = document.querySelector('#app');
const KEY = 'gali-english-club-v2'; // Older lesson progress stays untouched under v1.
let storageOK = true;
let saved;
try { saved = JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { saved = {}; storageOK = false; }
if (!saved || typeof saved !== 'object' || Array.isArray(saved)) saved = {};
let group = /^Class [AB] · Pair [1-5]$/.test(saved.group) ? saved.group : 'Class A · Pair 1';
let records = saved.records && typeof saved.records === 'object' && !Array.isArray(saved.records) ? saved.records : {};
let lesson = null;
const steps = ['Talk', 'Read', 'Answer', 'Write', 'Finish'];
const minutes = [2,8,8,10,2];
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){if(lesson){const current=records[key(lesson)];if(current)current.updatedAt=new Date().toISOString();}try{localStorage.setItem(KEY,JSON.stringify({group,records}));}catch{storageOK=false;}}
function key(l){return `${group}::${l.id}`;}
function record(l){const k=key(l); if(!records[k] || typeof records[k] !== 'object' || !Array.isArray(records[k].answers) || !Array.isArray(records[k].checks)) records[k]={step:0,answers:l.questions.map(()=>null),attempts:l.questions.map(()=>0),checks:[false,false,false],reflection:'',done:false}; const r=records[k];if(!Number.isInteger(r.step)||r.step<0||r.step>4)r.step=0;if(!Array.isArray(r.attempts))r.attempts=[];for(let i=0;i<l.questions.length;i++){if(r.answers[i]===undefined)r.answers[i]=null;if(!Number.isInteger(r.attempts[i]))r.attempts[i]=0;}return r;}
function focusHeading(){const h=app.querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo(0,0);}
function home(){lesson=null;app.innerHTML=`${storageOK?'':'<div role="alert" class="storage-alert">Progress cannot be saved in this browser. You can still do the activities. ההתקדמות לא תישמר בדפדפן זה.</div>'}<section class="hero"><div><span class="eyebrow">Your next little adventure</span><h1>Let’s read.<br>Let’s have fun!</h1><p>Read a short story with a friend. Talk together. Write in your notebook.</p><p class="tagline" dir="rtl">קוראים יחד • חושבים בתורות • כותבים במחברת</p></div><div class="art" aria-hidden="true"><div class="book">Aa</div><span class="sticker">✦</span><span class="star">✧</span></div></section><div class="setup"><strong>👋 Choose your team</strong><label>Class / כיתה <select id="class">${['A','B'].map(v=>`<option ${group.includes(`Class ${v}`)?'selected':''}>${v}</option>`).join('')}</select></label><label>Pair / זוג <select id="pair">${[1,2,3,4,5].map(v=>`<option ${group.endsWith(String(v))?'selected':''}>${v}</option>`).join('')}</select></label><small>No names needed · בלי שמות</small></div><div class="resume-entry"><button id="resume-open">🔑 We have a code / יש לנו קוד המשך</button><p dir="rtl">עברתם מחשב? בחרו כיתה וזוג למעלה, ואז הזינו את הקוד מהמחברת.</p></div><div class="start-guide" dir="rtl"><strong>איך מתחילים?</strong><ol><li>בחרו למעלה את הכיתה ואת מספר הזוג שלכם.</li><li>הכינו מחברת ועיפרון לכל ילד.</li><li>בחרו שיעור ולחצו על הכפתור הירוק ״התחילו כאן״.</li></ol></div><div class="sectionhead"><h2>Choose a story / בחרו סיפור</h2><span class="muted">16 stories · Two levels / שתי רמות</span></div>${[1,2].map(level=>`<section class="story-level"><h2>${level===1?'Level 1 · Read and explore / קוראים ומגלים':'Level 2 · A little more challenge / עוד קצת אתגר'}</h2><p dir="rtl">${level===1?'סיפורים קצרים · 4 שאלות הבנה ו־2 שאלות שיחה לכל סיפור':'סיפורים ארוכים מעט יותר · 6 שאלות הבנה ו־2 שאלות שיחה לכל סיפור'}</p><div class="grid">${LESSONS.filter(l=>l.level===level).map(l=>{const r=record(l);return `<article class="card"><div class="icon" aria-hidden="true">${l.icon}</div><span class="eyebrow">${String(LESSONS.indexOf(l)+1).padStart(2,'0')} / ${l.tag}</span><h3>${l.title}</h3><p>${l.goal}</p><button data-lesson="${l.id}" class="${r.done?'light':''}">${r.done?'Read again / קראו שוב':r.step?'Continue / המשיכו':'Start here / התחילו כאן'}</button></article>`;}).join('')}</div></section>`).join('')}<p class="muted tagline">Have a notebook and pencil ready. Progress stays in this browser.<br><span dir="rtl">בחרו בכל שיעור את אותה כיתה ואת אותו מספר זוג. בבית ההתקדמות נפרדת.</span></p>`;
document.querySelector('#resume-open').onclick=showResumeEntry;app.querySelectorAll('select').forEach(s=>s.onchange=()=>{group=`Class ${document.querySelector('#class').value} · Pair ${document.querySelector('#pair').value}`;persist();home();});app.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{lesson=LESSONS.find(l=>l.id===b.dataset.lesson);const current=record(lesson);if(!current.startedAt&&!current.step&&!current.done&&!current.answers.some(Number.isInteger)){current.startedAt=new Date().toISOString();}if(current.done)current.step=0;persist();render();focusHeading();showResumeSave(true);});}
function textBlock(){return `<div class="reading">${lesson.text.split('\n').map((p,i)=>`<div class="story-part"><span class="reader-label">${i%2===0?'Partner 1 reads / ילד 1 קורא':'Partner 2 reads / ילד 2 קורא'}</span><p>${esc(p)}</p></div>`).join('')}</div>`;}
function question(i,r){const q=lesson.questions[i],correct=r.answers[i]===q.answer,answered=Number.isInteger(r.answers[i]);return `<section><h3>${i+1}. ${q.q}</h3><div class="choices">${q.choices.map((c,n)=>`<button data-q="${i}" data-choice="${n}" ${correct?'disabled':''} class="${r.answers[i]===n?'selected':''}">${String.fromCharCode(65+n)}. ${c}</button>`).join('')}</div><div aria-live="polite">${answered?`<div tabindex="-1" id="feedback-${i}" class="feedback ${correct?'success':''}">${correct?'✓ Yes! '+q.why:'Not yet. Read the hint and try again. '+q.hint}</div>`:''}</div><details><summary>💡 Click for help / לחצו לרמז</summary><p>${q.hint}</p></details></section>`;}
function render(){const r=record(lesson),s=r.step;let body='';
if(s===0)body=`<h2>Let’s talk / בואו נדבר</h2><p class="task-prompt">${lesson.warm}</p><div class="coach"><strong>Today we will…</strong>${lesson.goal}</div><p>No typing yet. Just talk!</p><p dir="rtl">לא צריך להקליד. כל ילד אומר רעיון אחד בקול.</p>`;
if(s===1)body=`<h2>Read the story below / קראו כאן</h2><p class="muted">Read one part each. Scroll down to keep reading.</p><h3>${lesson.title}</h3>${textBlock()}<h3>Words to help / מילים שיעזרו לכם</h3><div class="words">${lesson.words.map(w=>`<div class="word-card"><strong>${w[0]}</strong><p>${w[1]}<br><span lang="he" dir="rtl">${w[2]}</span></p></div>`).join('')}</div><p dir="rtl">קראו שוב משפט שלא הבנתם. אפשר לבקש מבן או בת הזוג לקרוא איתכם.</p>`;
if(s===2)body=`<h2>Pick an answer / בחרו תשובה</h2><div class="switch">🔄 Partner 2 uses the mouse now.<br><span dir="rtl">מחליפים: ילד 2 מפעיל את העכבר. שניכם חושבים יחד.</span></div><details open class="story-reference"><summary>📖 Story / הסיפור כאן — אפשר לקרוא שוב</summary>${textBlock()}</details>${lesson.questions.map((_,i)=>question(i,r)).join('')}<div class="coach"><strong>Now talk / עכשיו משוחחים</strong><ol>${lesson.openQuestions.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p>Take turns. Give a reason and point to a story clue.</p><p dir="rtl">ענו בתורות על שתי השאלות. כל ילד מסביר ומראה פרט מהסיפור שעוזר לתשובה. כתבו במחברת תשובה אחת במשפט מלא. אין צורך להקליד כאן.</p></div>`;
if(s===3)body=`<h2>Write in your notebook / כותבים במחברת</h2><p class="task-prompt">${lesson.write}</p><ol class="writing-steps">${lesson.writeSteps.map(t=>`<li>${t}</li>`).join('')}</ol><div class="coach"><strong>Start like this / אפשר להתחיל כך</strong>${lesson.starter}<p dir="rtl">השלימו במילים שלכם. כל ילד כותב במחברת שלו.</p></div><p class="muted">Think: 2 minutes · Write: 6 minutes · Check: 2 minutes</p><details open class="story-reference"><summary>📖 Story / הסיפור לעזרה בכתיבה</summary>${textBlock()}</details><h3>Check your work / בדקו את הכתיבה</h3><p dir="rtl">כל אחד קורא את מה שכתב. סמנו כל ריבוע רק אחרי ששניכם בדקתם.</p>${lesson.check.map((c,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${r.checks[i]?'checked':''}>${c}</label>`).join('')}<div class="writing-evidence"><label for="writing-sample"><strong>Type one sentence from your notebook / הקלידו משפט אחד מהמחברת</strong></label><p dir="rtl">המשפט יופיע בדוח למורה. בזוג: כתבו משפט מכל מחברת. אין להזין שמות או פרטים אישיים.</p><textarea id="writing-sample" maxlength="800" placeholder="My sentence…">${esc(r.writingSample||'')}</textarea><p class="muted" dir="rtl">האתר שומר את המשפט, אך לא בודק את איכותו או את המחברת.</p></div><details><summary>⭐ Finished early? Click here / סיימתם מוקדם? לחצו כאן</summary><p>${lesson.challenge}</p></details>`;
if(s===4)body=`<h2>Tell your partner / ספרו לבן או בת הזוג</h2><p class="task-prompt">${lesson.exit}</p><div class="coach"><strong>Each child answers out loud.</strong><span dir="rtl">כל ילד אומר תשובה בקול ומראה לבן או בת הזוג את המחברת.</span></div><label for="reflection">Want to type your idea? / אפשר גם להקליד — לא חובה</label><textarea id="reflection" maxlength="400" placeholder="We think…">${esc(r.reflection||'')}</textarea><p class="muted" dir="rtl">התשובה נשמרת במחשב הזה. אין בדיקה אוטומטית. אל תכתבו שמות או פרטים אישיים.</p><details><summary>💡 Click to see an example / לחצו לדוגמה</summary><p>${lesson.model}</p><p class="muted" dir="rtl">זו דוגמה מוכנה מראש, לא בדיקה של התשובה שלכם.</p></details><p dir="rtl">כתבו במחברת את התאריך ואת שם הסיפור. לחצו למטה על ״סיימנו״.</p>`;
const instructions=[
 ['Get a notebook and pencil. Take turns answering the question below. Then click “Open the story”.','הכינו מחברת ועיפרון. ענו בקול על השאלה שבתיבה, כל ילד בתורו. לסיום לחצו למטה על ״פתחו את הסיפור״.'],
 ['Read the story below. Partner 1 reads part 1. Partner 2 reads part 2. Take turns until the end.','הסיפור כבר פתוח למטה — גללו כדי לקרוא. ילד 1 קורא את החלק הראשון, ילד 2 את השני. ממשיכים בתורות עד הסוף. אחר כך לוחצים על ״עברו לשאלות״.'],
 ['Read each question. Talk together. Click one answer. If it is not right, use the hint and try again.','קראו כל שאלה. חשבו יחד ולחצו על תשובה אחת. אם טעיתם, קראו את הרמז ונסו שוב. גללו למטה אל השאלות; הסיפור פתוח לעזרה. בסיום ענו על שתי שאלות השיחה וכתבו תשובה אחת במחברת.'],
 ['Open your own notebook. Follow the three steps below. Then read and check your writing.','כל ילד פותח את המחברת שלו. בצעו את שלוש ההוראות למטה. הפתיחות למשפטים יעזרו לכם. בסוף קראו ובדקו את הכתיבה.'],
 ['Each child answers the question out loud. Show your notebook to your partner. Then click “Finish”.','כל ילד עונה בקול על השאלה. הראו זה לזה את הכתיבה במחברת. אפשר להקליד תשובה, אבל לא חייבים. בסוף לחצו על ״סיימנו״.']
];
const nextLabels=['Open the story / פתחו את הסיפור →','Go to questions / עברו לשאלות →','Go to notebooks / עברו למחברות →','Let’s finish / עברו לסיכום →','Finish / סיימנו ✓'];

app.innerHTML=`<div class="lessonhead"><div><span class="eyebrow">${group} · Adventure ${LESSONS.indexOf(lesson)+1}</span><h1>${lesson.icon} ${lesson.title}</h1></div><button class="quiet" id="home">Save for later / שמרו להמשך</button></div>${bookmarkPanel()}<div class="progress" aria-label="Step ${s+1} of 5">${steps.map((_,i)=>`<span class="${i<=s?'active':''}"></span>`).join('')}</div><div class="stage"><aside class="side"><div class="bigicon">${lesson.icon}</div><h3>${steps[s]}</h3><span class="badge">About ${minutes[s]} minutes</span><p>Step ${s+1} of 5</p><p>${lesson.goal}</p><p class="muted">Suggested times — no countdown. Work at your pace.</p></aside><article class="panel"><div class="step-instructions"><span class="badge">Step ${s+1} of 5 · שלב ${s+1} מתוך 5</span><h2>What do we do? / מה עושים?</h2><p>${instructions[s][0]}</p><p lang="he" dir="rtl">${instructions[s][1]}</p></div>${body}<div class="actions"><button class="quiet" id="back">${s?'← Back / חזרה':'← Stories / סיפורים'}</button><button id="next">${nextLabels[s]}</button></div><p id="step-message" role="status"></p></article></div>`;
document.querySelector('#home').onclick=()=>showResumeSave();document.querySelector('#back').onclick=()=>{if(s){r.step--;persist();render();focusHeading();}else home();};document.querySelector('#next').onclick=()=>{if(s===2&&!lesson.questions.every((q,i)=>r.answers[i]===q.answer)){document.querySelector('#step-message').textContent='Answer all the questions first. Click “לחצו לרמז” for help. ענו על כל שאלות הבחירה לפני המעבר למחברת.';return;}if(s===3&&!writingReady(r)){document.querySelector('#step-message').textContent='כתבו משפט מהמחברת (לפחות שלוש מילים) וסמנו את שלוש הבדיקות לפני ההמשך.';return;}if(s===4&&!lesson.questions.every((q,i)=>r.answers[i]===q.answer)){r.step=2;persist();render();document.querySelector('#step-message').textContent='נשלים את שאלות ההבנה לפני הסיום. קוד המשך מעביר מיקום בלבד, לא תשובות.';return;}if(s===4&&!writingReady(r)){r.step=3;persist();render();document.querySelector('#step-message').textContent='לפני הסיום, שמרו משפט מהמחברת ובדקו את הכתיבה.';return;}if(s<4){r.step++;persist();render();focusHeading();}else{r.done=true;r.completedAt=new Date().toISOString();r.evidenceVersion=1;persist();complete();focusHeading();}};
app.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.q);r.answers[i]=Number(b.dataset.choice);r.attempts[i]=(r.attempts[i]||0)+1;persist();render();const target=app.querySelector(`[data-q="${i}"][data-choice="${r.answers[i]}"]`);if(target&&!target.disabled)target.focus();else document.querySelector(`#feedback-${i}`)?.focus();});app.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>{r.checks[Number(c.dataset.check)]=c.checked;persist();});const writing=document.querySelector('#writing-sample');if(writing)writing.oninput=()=>{r.writingSample=writing.value;persist();};const input=document.querySelector('#reflection');if(input)input.oninput=()=>{r.reflection=input.value;persist();};}
function complete(){app.innerHTML=`<div class="panel complete"><div class="bigicon">🌟</div><span class="eyebrow">Adventure complete</span><h1>Well done!<br>You finished the story.</h1><p>${lesson.title}</p><div class="stats"><span>📖 Read together</span><span>💬 Shared ideas</span><span>✏️ Notebook time</span></div>${bookmarkPanel()}<p>Show your notebook to your teacher before starting another story.</p><p dir="rtl">הראו למורה את המחברת לפני מעבר לסיפור נוסף. אל תשכחו לרשום את קוד ההמשך המעודכן.</p><button id="finished-report">Show my report / הציגו את הדוח שלי</button><p class="muted" dir="rtl">הסיום מציין שסיימתם את המסלול. המורה תבדוק את הכתיבה במחברת.</p><button id="return">Back to stories / חזרה לסיפורים →</button></div>`;document.querySelector('#finished-report').onclick=()=>teacher(group);document.querySelector('#return').onclick=()=>{home();focusHeading();};}
function teacher(selected='all') {
  lesson=null;
  const groups=[...new Set(Object.keys(records).map(k=>k.split('::')[0]))].filter(g=>/^Class [AB] · Pair [1-5]$/.test(g));
  if(selected!=='all'&&!groups.includes(selected))selected='all';
  const report=window.EnglishReport.build(records,LESSONS,selected);
  app.innerHTML=`<article class="panel teacher"><h1>דוח עבודה למורה</h1><p><strong>הדוח מציג רק מה שנשמר בדפדפן הזה, בכתובת האתר הזאת.</strong> אין איסוף מרחוק מהמחשבים בכיתה. הכתיבה במחברת אינה נבדקת אוטומטית. ״סומן סיום״ אינו הוכחה לביצוע מלא.</p><div class="notice">לחיפוש העבודה מהיום: פתחו במחשב ובדפדפן של התלמיד את אותו קישור שבו עבד, ואז לחצו ״למורה״. אם אין רשומות, בדקו כיתה/זוג, דפדפן וקישור. הקישור המקומי והקישור הציבורי שומרים בנפרד. אין דרך לשחזר מכאן נתונים שנמחקו או מעולם לא נשמרו.</div><label for="report-group">איזה זוג להציג?</label><select id="report-group"><option value="all">כל הזוגות במחשב הזה</option>${groups.map(g=>`<option value="${esc(g)}" ${selected===g?'selected':''}>${esc(g)}</option>`).join('')}</select><div class="report-actions"><button id="print-report">הדפסה / שמירה כ־PDF</button><button id="download-report">הורדת דוח קריא</button><button class="quiet" id="backup-report">גיבוי נתונים JSON</button><button class="quiet" id="teacher-home">חזרה לשיעורים</button></div><p id="export-status" role="status"></p><div id="readable-report">${report.html}</div><details><summary>לא מצליחים להוריד? הציגו טקסט להעתקה</summary><label for="report-text">אפשר לבחור ולהעתיק את הדוח, או לצלם את המסך</label><textarea id="report-text" readonly rows="12">${esc(report.text)}</textarea></details><details><summary>איך לעבוד מחר?</summary><ol><li>תנו לכל תלמיד או זוג מספר קבוע בכיתה A או B. אין להשתמש באותו מספר לשני תלמידים שעובדים בנפרד באותו דפדפן.</li><li>הנחו לעבוד על סיפור אחד שבחרתם, ולא לעבור לסיפור הבא לפני בדיקת המחברת.</li><li>בתחילת השיעור מופיע קוד מיקום. הוא משתנה עם כל שלב; לפני העצירה יש להעתיק את הקוד המעודכן.</li><li>בסיום הציגו את הדוח על מחשב התלמיד ושמרו או הדפיסו אותו. המשפט המוקלד הוא דוגמת כתיבה בלבד, לא כל עבודת המחברת.</li></ol></details></article>`;
  document.querySelector('#report-group').onchange=e=>teacher(e.target.value);
  document.querySelector('#teacher-home').onclick=home;
  document.querySelector('#print-report').onclick=()=>window.print();
  document.querySelector('#download-report').onclick=()=>downloadReport(window.EnglishReport.document(report),'english-club-report.html','text/html;charset=utf-8');
  document.querySelector('#backup-report').onclick=()=>downloadReport(JSON.stringify({exportedAt:new Date().toISOString(),scope:'Local browser only',group,records},null,2),'english-club-backup.json','application/json');
  focusHeading();
}
function downloadReport(content,name,type){
  const status=document.querySelector('#export-status');
  try {const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent='בקשת ההורדה נשלחה. אם לא נוצר קובץ, השתמשו בהדפסה או בטקסט להעתקה למטה. הדוח עצמו גלוי כאן גם בלי הורדה.';}
  catch {status.textContent='הדפדפן חסם את ההורדה. הדוח מוצג למטה; אפשר להדפיס, להעתיק או לצלם אותו.';}
}
function writingReady(r){return Array.isArray(r.checks)&&r.checks.length===3&&r.checks.every(v=>v===true)&&typeof r.writingSample==='string'&&r.writingSample.trim().split(/\s+/).length>=3;}
function bookmarkPanel(){const code=window.ResumeCodes.encode(lesson.id,record(lesson).step);return `<section class="bookmark-banner" aria-label="קוד המשך"><div><strong>Resume code / קוד המשך</strong><output dir="ltr">${code}</output></div><p dir="rtl">העתיקו למחברת לפני שסוגרים. הקוד משתנה כשעוברים שלב ומחזיר לתחילת השלב בלבד — הוא אינו חשבון אישי ולא שומר תשובות.</p>${storageOK?'':'<p role="alert" dir="rtl">השמירה במחשב לא זמינה. הקוד יחזיר רק למיקום; הציגו למורה את הדוח לפני סגירת החלון.</p>'}</section>`;}

function resumeDialog(html) {
  const previous = document.activeElement;
  const dialog = document.createElement('dialog');
  dialog.className = 'resume-dialog';
  dialog.setAttribute('aria-labelledby','resume-title');
  dialog.innerHTML = html;
  document.body.append(dialog);
  dialog.addEventListener('close',()=>{dialog.remove();if(previous?.isConnected)previous.focus();});
  dialog.showModal();
  return dialog;
}
function showResumeSave(atStart=false) {
  persist();
  const code = window.ResumeCodes.encode(lesson.id,record(lesson).step);
  const dialog = resumeDialog(`<h2 id="resume-title">${atStart?'Your first code / קוד לתחילת העבודה':'Save for later / שמרו להמשך'}</h2><p dir="rtl">העתיקו את הקוד למחברת של כל אחד מכם. כתבו לידו את שם הסיפור ואת מספר הזוג. הקוד אינו אישי ואינו מזהה אתכם. הוא משתנה כשמתקדמים, ולכן חשוב להעתיק את הקוד המעודכן לפני שסוגרים.</p><p><strong>${esc(lesson.title)}</strong> · Step ${record(lesson).step+1} / שלב ${record(lesson).step+1}</p><label for="saved-code">Your code / הקוד שלכם</label><input id="saved-code" class="code-value" value="${code}" readonly dir="ltr"><p dir="rtl">בשיעור הבא: פתחו את האתר, בחרו כיתה וזוג ולחצו על ״יש לנו קוד המשך״.</p><p class="muted" dir="rtl">הקוד שומר רק את השיעור והשלב. במחשב אחר תשובות קודמות לא יופיעו, וייתכן שתענו שוב על שאלות באותו שלב. שמרו קוד חדש אחרי שתתקדמו.</p><div class="resume-buttons"><button id="code-exit">We wrote it down / כתבנו במחברת — יציאה</button><button class="quiet" id="code-stay">${atStart?'We wrote it down — start / רשמנו — מתחילים':'Keep working / ממשיכים לעבוד'}</button></div>`);
  dialog.querySelector('#code-stay').onclick=()=>dialog.close();
  dialog.querySelector('#code-exit').onclick=()=>{dialog.close();home();focusHeading();};
}
function showResumeEntry() {
  const dialog=resumeDialog(`<h2 id="resume-title">Continue your story / ממשיכים בסיפור</h2><p dir="rtl">הקלידו את שש הספרות שכתבתם במחברת. אפשר גם בלי המקף.</p><p dir="ltr">${esc(group)}</p><form id="resume-form"><label for="resume-code">Your code / קוד המשך</label><input id="resume-code" inputmode="numeric" type="text" dir="ltr" maxlength="16" autocomplete="off" required aria-describedby="resume-error"><p id="resume-error" role="status" dir="rtl"></p><button type="submit">Check code / בדקו קוד</button></form><div id="resume-preview"></div><button class="quiet" id="resume-cancel">Cancel / ביטול</button>`);
  dialog.querySelector('#resume-cancel').onclick=()=>dialog.close();
  const input=dialog.querySelector('#resume-code'), preview=dialog.querySelector('#resume-preview'), error=dialog.querySelector('#resume-error');
  input.oninput=()=>{preview.innerHTML='';error.textContent='';input.removeAttribute('aria-invalid');};
  dialog.querySelector('#resume-form').onsubmit=e=>{
    e.preventDefault();
    const bookmark=window.ResumeCodes.decode(input.value);
    const target=bookmark && LESSONS.find(l=>l.id===bookmark.id);
    if(!target){preview.innerHTML='';error.textContent='הקוד לא מתאים. בדקו שהעתקתם את כל שש הספרות ונסו שוב.';input.setAttribute('aria-invalid','true');input.focus();return;}
    error.textContent='';input.removeAttribute('aria-invalid');
    preview.innerHTML=`<div class="coach"><strong>${esc(target.title)}</strong>Step ${bookmark.step+1}: ${steps[bookmark.step]}<p dir="rtl">נחזור לתחילת שלב ${bookmark.step+1}. הקוד אינו מעביר תשובות ממחשב אחר. עבודה שכבר שמורה במחשב הזה תישאר.</p></div><button id="resume-start">Continue here / המשיכו מכאן →</button>`;
    preview.querySelector('#resume-start').onclick=()=>{lesson=target;record(lesson).step=bookmark.step;persist();dialog.close();render();focusHeading();};
    preview.querySelector('#resume-start').focus();
  };
  input.focus();
}

document.querySelector('.brand').onclick=e=>{e.preventDefault();home();focusHeading();};document.querySelector('#teacher').onclick=()=>teacher();home();
